export declare const convertshape: string
export declare const microphone_slash_1: string
export declare const smart_home: string
export declare const profile_delete: string
export declare const import_2: string
export declare const arrow_square_up: string
export declare const directbox_notif: string
export declare const heart_circle: string
export declare const bag_tick: string
export declare const gallery_remove: string
export declare const triangle: string
export declare const toggle_on: string
export declare const sun_1: string
export declare const driver: string
export declare const slider_vertical_1: string
export declare const task: string
export declare const clipboard_close: string
export declare const shop_add: string
export declare const toggle_on_circle: string
export declare const musicnote: string
export declare const eraser: string
export declare const like: string
export declare const receipt: string
export declare const pause_circle: string
export declare const subtitle: string
export declare const printer_slash: string
export declare const paintbucket: string
export declare const search_zoom_in_1: string
export declare const arrow_down: string
export declare const battery_disable: string
export declare const quote_down: string
export declare const lamp_1: string
export declare const ghost: string
export declare const textalign_left: string
export declare const heart_tick: string
export declare const brifecase_timer: string
export declare const shapes_1: string
export declare const quote_down_circle: string
export declare const timer_start: string
export declare const archive_minus: string
export declare const shield_search: string
export declare const gemini: string
export declare const location_add: string
export declare const refresh_circle: string
export declare const sound: string
export declare const card_send: string
export declare const house: string
export declare const buildings_2: string
export declare const card_coin: string
export declare const trush_square: string
export declare const note_favorite: string
export declare const money_add: string
export declare const wind: string
export declare const receipt_2_1: string
export declare const rotate_left: string
export declare const menu_1: string
export declare const play_circle: string
export declare const arrow_square_left: string
export declare const picture_frame: string
export declare const information: string
export declare const document_text_1: string
export declare const arrange_square: string
export declare const refresh_square_2: string
export declare const repeat: string
export declare const import_1: string
export declare const profile_remove: string
export declare const path: string
export declare const brush_4: string
export declare const gallery_tick: string
export declare const gps_slash: string
export declare const presention_chart: string
export declare const password_check: string
export declare const tick_square: string
export declare const chart: string
export declare const document_like: string
export declare const map_1: string
export declare const tag_2: string
export declare const aquarius: string
export declare const money_time: string
export declare const document_forward: string
export declare const translate: string
export declare const more_circle: string
export declare const audio_square: string
export declare const wallet_search: string
export declare const user: string
export declare const money_change: string
export declare const arrow: string
export declare const message_text_1: string
export declare const home_trend_up: string
export declare const rotate_right_1: string
export declare const card_receive: string
export declare const heart_search: string
export declare const sidebar_left: string
export declare const quote_up: string
export declare const format_square: string
export declare const like_dislike: string
export declare const arrow_square: string
export declare const forward_5_seconds: string
export declare const clipboard_tick: string
export declare const edit_2: string
export declare const milk: string
export declare const home: string
export declare const shop: string
export declare const copyright: string
export declare const wallet_2: string
export declare const hierarchy_2: string
export declare const play_cricle: string
export declare const card_tick_1: string
export declare const textalign_justifycenter: string
export declare const received: string
export declare const music: string
export declare const music_square_search: string
export declare const brush_1: string
export declare const arrow_up_3: string
export declare const star_1: string
export declare const dollar_circle: string
export declare const card_edit: string
export declare const bag_happy: string
export declare const money_tick: string
export declare const message_search: string
export declare const support: string
export declare const logout: string
export declare const camera_slash: string
export declare const message_notif: string
export declare const flag_2: string
export declare const creative_commons: string
export declare const signpost: string
export declare const candle: string
export declare const quote_up_square: string
export declare const brifecase_cross: string
export declare const ticket: string
export declare const export_file: string
export declare const blur: string
export declare const convertshape_2: string
export declare const refresh_right_square: string
export declare const call_remove: string
export declare const crop: string
export declare const text_italic: string
export declare const calendar_1: string
export declare const tag: string
export declare const user_tag: string
export declare const sidebar_top: string
export declare const briefcase: string
export declare const location_slash: string
export declare const arrow_up_2: string
export declare const align_bottom: string
export declare const calendar_add: string
export declare const arrow_circle_up: string
export declare const music_square_add: string
export declare const wallet_3: string
export declare const calendar_search: string
export declare const hierarchy_3: string
export declare const wallet_1: string
export declare const directbox_send: string
export declare const cloud_plus: string
export declare const direct_right: string
export declare const chart_fail: string
export declare const brush_2: string
export declare const moneys: string
export declare const map: string
export declare const sidebar_right: string
export declare const sms_notification: string
export declare const microphone: string
export declare const home_trend_down: string
export declare const calendar_circle: string
export declare const music_filter: string
export declare const book_square: string
export declare const mobile_programming: string
export declare const transaction_minus: string
export declare const airpods: string
export declare const user_square: string
export declare const grammerly: string
export declare const ticket_star: string
export declare const arrow_3: string
export declare const smileys: string
export declare const monitor_mobbile: string
export declare const pen_tool_2: string
export declare const message_circle: string
export declare const arrow_2: string
export declare const devices: string
export declare const discount_shape: string
export declare const fatrows: string
export declare const mouse_square: string
export declare const percentage_square: string
export declare const magic_star: string
export declare const shield_tick: string
export declare const maximize: string
export declare const radar: string
export declare const calendar_2: string
export declare const cpu_setting: string
export declare const lock_slash: string
export declare const arrow_up_1: string
export declare const brush_3: string
export declare const warning_2: string
export declare const message_add: string
export declare const sms_search: string
export declare const bubble: string
export declare const search_status: string
export declare const folder_open: string
export declare const chart_2: string
export declare const path_2: string
export declare const keyboard: string
export declare const notification_circle: string
export declare const filter_tick: string
export declare const microphone_2: string
export declare const attach_circle: string
export declare const location_tick: string
export declare const video_tick: string
export declare const profile_2user: string
export declare const save_minus: string
export declare const grid_7: string
export declare const mask_2: string
export declare const user_tick: string
export declare const lock: string
export declare const box_remove: string
export declare const call_outgoing: string
export declare const buildings: string
export declare const health: string
export declare const shopping_bag: string
export declare const language_circle: string
export declare const bag_2: string
export declare const filter_search: string
export declare const slider_vertical: string
export declare const search_zoom_in: string
export declare const money_3: string
export declare const cloud_drizzle: string
export declare const money_2: string
export declare const empty_wallet_tick: string
export declare const dislike: string
export declare const driver_refresh: string
export declare const coin_1: string
export declare const frame_1: string
export declare const clipboard: string
export declare const lamp_on: string
export declare const instagram: string
export declare const receipt_square: string
export declare const link: string
export declare const radar_1: string
export declare const empty_wallet: string
export declare const toggle_off: string
export declare const note_1: string
export declare const key: string
export declare const grid_6: string
export declare const money_forbidden: string
export declare const box_2: string
export declare const arrow_right: string
export declare const brush: string
export declare const stop_circle: string
export declare const three_d_rotate: string
export declare const chart_3: string
export declare const ship: string
export declare const chart_1: string
export declare const driver_2: string
export declare const backward_15_seconds: string
export declare const calendar_tick: string
export declare const programming_arrows: string
export declare const receive_square: string
export declare const minus_square: string
export declare const settings: string
export declare const row_horizontal: string
export declare const gallery_favorite: string
export declare const cloud_snow: string
export declare const text_bold: string
export declare const mask_1: string
export declare const grid_4: string
export declare const status_up: string
export declare const volume_cross: string
export declare const book_saved: string
export declare const global_search: string
export declare const forward_item: string
export declare const note_text: string
export declare const game: string
export declare const archive: string
export declare const frame_3: string
export declare const close_circle: string
export declare const omega_square: string
export declare const textalign_right: string
export declare const backward_5_seconds: string
export declare const bookmark_2: string
export declare const notification_favorite: string
export declare const code_1: string
export declare const shield: string
export declare const video_circle: string
export declare const shop_remove: string
export declare const kanban: string
export declare const align_vertically: string
export declare const frame_2: string
export declare const note: string
export declare const size: string
export declare const import_file: string
export declare const direct_up: string
export declare const home_hashtag: string
export declare const gallery: string
export declare const global_edit: string
export declare const radar_2: string
export declare const note_2: string
export declare const grid_5: string
export declare const shield_cross: string
export declare const profile_add: string
export declare const cloud_notif: string
export declare const add_square: string
export declare const discover: string
export declare const receipt_disscount: string
export declare const sms: string
export declare const link_circle: string
export declare const box_1: string
export declare const voice_square: string
export declare const card_pos: string
export declare const tag_user: string
export declare const message_question: string
export declare const wifi_square: string
export declare const message_time: string
export declare const ram_2: string
export declare const battery_charging: string
export declare const shapes: string
export declare const rotate_left_1: string
export declare const repeate_music: string
export declare const slash: string
export declare const login: string
export declare const radio: string
export declare const devices_1: string
export declare const sagittarius: string
export declare const ticket_2: string
export declare const grid_edit: string
export declare const book: string
export declare const note_add: string
export declare const grid_1: string
export declare const heart_slash: string
export declare const scissor: string
export declare const timer_pause: string
export declare const user_minus: string
export declare const folder_favorite: string
export declare const wallet: string
export declare const backward_10_seconds: string
export declare const bucket_circle: string
export declare const paperclip_2: string
export declare const coffee: string
export declare const unlimited: string
export declare const flash: string
export declare const code: string
export declare const money_4: string
export declare const cake: string
export declare const icon: string
export declare const user_cirlce_add: string
export declare const medal_star: string
export declare const convert_three_d_cube: string
export declare const teacher: string
export declare const flag: string
export declare const pen_remove: string
export declare const gps: string
export declare const search_status_1: string
export declare const like_tag: string
export declare const gameboy: string
export declare const flash_circle_1: string
export declare const stop: string
export declare const search_normal: string
export declare const house_2: string
export declare const card_remove_1: string
export declare const arrow_circle_left: string
export declare const document_previous: string
export declare const row_vertical: string
export declare const pen_close: string
export declare const save_2: string
export declare const save_remove: string
export declare const emoji_happy: string
export declare const message_tick: string
export declare const gemini_2: string
export declare const buy_crypto: string
export declare const ruler: string
export declare const music_square: string
export declare const sms_tracking: string
export declare const document_favorite: string
export declare const cpu: string
export declare const document_1: string
export declare const call_slash: string
export declare const receive_square_2: string
export declare const user_remove: string
export declare const scissor_1: string
export declare const music_dashboard: string
export declare const record: string
export declare const ranking_1: string
export declare const grid_2: string
export declare const video_time: string
export declare const stickynote: string
export declare const category: string
export declare const battery_full: string
export declare const bluetooth_circle: string
export declare const chart_21: string
export declare const cloud_remove: string
export declare const document: string
export declare const chart_success: string
export declare const check: string
export declare const empty_wallet_change: string
export declare const notification_1: string
export declare const ranking: string
export declare const airdrop: string
export declare const mirroring_screen: string
export declare const trend_up: string
export declare const filter_add: string
export declare const hospital: string
export declare const archive_book: string
export declare const direct_down: string
export declare const arrange_circle_2: string
export declare const bluetooth: string
export declare const global: string
export declare const routing_2: string
export declare const headphones: string
export declare const additem: string
export declare const finger_scan: string
export declare const gallery_slash: string
export declare const frame_4: string
export declare const empty_wallet_time: string
export declare const category_2: string
export declare const main_component: string
export declare const wifi: string
export declare const hashtag_up: string
export declare const route_square: string
export declare const document_code_2: string
export declare const watch: string
export declare const card: string
export declare const video_add: string
export declare const directbox_default: string
export declare const backward_item: string
export declare const wallet_check: string
export declare const slider: string
export declare const arrow_circle_right: string
export declare const archive_add: string
export declare const grid_3: string
export declare const archive_tick: string
export declare const code_circle: string
export declare const key_square: string
export declare const sidebar_bottom: string
export declare const user_add: string
export declare const add: string
export declare const truck_fast: string
export declare const speedometer: string
export declare const document_code: string
export declare const book_1: string
export declare const convert_card: string
export declare const people: string
export declare const quote_down_square: string
export declare const info_circle: string
export declare const cloud_fog: string
export declare const bag_cross: string
export declare const ticket_expired: string
export declare const arrow_right_1: string
export declare const smallcaps: string
export declare const watch_status: string
export declare const copy: string
export declare const receipt_add: string
export declare const bag_tick_2: string
export declare const call_calling: string
export declare const maximize_3: string
export declare const element_4: string
export declare const bag: string
export declare const sun_fog: string
export declare const arrange_circle: string
export declare const hierarchy_square_3: string
export declare const align_horizontally: string
export declare const hierarchy_square_2: string
export declare const box_add: string
export declare const hierarchy_square: string
export declare const refresh: string
export declare const cloud_cross: string
export declare const link_21: string
export declare const chart_square: string
export declare const hashtag_1: string
export declare const gallery_import: string
export declare const text: string
export declare const align_right: string
export declare const image: string
export declare const maximize_2: string
export declare const calendar_edit: string
export declare const folder_connection: string
export declare const card_slash: string
export declare const truck_tick: string
export declare const reserve: string
export declare const flash_1: string
export declare const simcard_1: string
export declare const search_favorite_1: string
export declare const lamp: string
export declare const minus_cirlce: string
export declare const scan: string
export declare const cloud_lightning: string
export declare const security_card: string
export declare const direct_inbox: string
export declare const link_1: string
export declare const document_cloud: string
export declare const command_square: string
export declare const heart_add: string
export declare const message_text: string
export declare const setting: string
export declare const grid_lock: string
export declare const three_dcube: string
export declare const volume_mute: string
export declare const previous: string
export declare const crown_1: string
export declare const arrow_right_2: string
export declare const paperclip: string
export declare const flash_circle: string
export declare const story: string
export declare const message_favorite: string
export declare const textalign_justifyleft: string
export declare const safe_home: string
export declare const document_copy: string
export declare const message: string
export declare const airpod: string
export declare const video_remove: string
export declare const sticker: string
export declare const award: string
export declare const trade: string
export declare const box_search: string
export declare const box: string
export declare const location_cross: string
export declare const format_circle: string
export declare const empty_wallet_remove: string
export declare const messages: string
export declare const mask: string
export declare const cloud_change: string
export declare const message_2: string
export declare const crown: string
export declare const broom: string
export declare const message_add_1: string
export declare const ruler_pen: string
export declare const eye_slash: string
export declare const play: string
export declare const backward: string
export declare const toggle_off_circle: string
export declare const directbox_receive: string
export declare const filter_remove: string
export declare const filter_edit: string
export declare const notification: string
export declare const text_block: string
export declare const driving: string
export declare const coin: string
export declare const verify: string
export declare const like_1: string
export declare const notification_bing: string
export declare const diagram: string
export declare const maximize_1: string
export declare const user_edit: string
export declare const airplane_square: string
export declare const send: string
export declare const barcode: string
export declare const direct: string
export declare const smart_car: string
export declare const user_octagon: string
export declare const mouse_1: string
export declare const bill: string
export declare const tag_cross: string
export declare const tick_circle: string
export declare const scroll: string
export declare const empty_wallet_add: string
export declare const simcard_2: string
export declare const play_add: string
export declare const speaker: string
export declare const archive_slash: string
export declare const convert: string
export declare const arrow_right_3: string
export declare const brifecase_tick: string
export declare const battery_empty: string
export declare const document_text: string
export declare const camera: string
export declare const link_2: string
export declare const printer: string
export declare const more_square: string
export declare const hashtag_down: string
export declare const redo: string
export declare const autobrightness: string
export declare const cloud_add: string
export declare const folder_minus: string
export declare const truck: string
export declare const user_search: string
export declare const discount_circle: string
export declare const quote_up_circle: string
export declare const pen_tool: string
export declare const note_remove: string
export declare const music_playlist: string
export declare const grid_8: string
export declare const arrow_bottom: string
export declare const security: string
export declare const more: string
export declare const bucket: string
export declare const receipt_1: string
export declare const document_download: string
export declare const emoji_sad: string
export declare const text_underline: string
export declare const back_square: string
export declare const element_2: string
export declare const glass: string
export declare const grid_eraser: string
export declare const cloud_minus: string
export declare const battery_empty_1: string
export declare const bus: string
export declare const firstline: string
export declare const textalign_center: string
export declare const arrow_left_3: string
export declare const arrow_left_2: string
export declare const export_1: string
export declare const trash: string
export declare const battery_3full: string
export declare const refresh_left_square: string
export declare const pen_add: string
export declare const monitor_recorder: string
export declare const record_circle: string
export declare const maximize_4: string
export declare const video_octagon: string
export declare const element_3: string
export declare const direct_left: string
export declare const dollar_square: string
export declare const scan_barcode: string
export declare const recovery_convert: string
export declare const element_equal: string
export declare const grid_9: string
export declare const computing: string
export declare const weight_1: string
export declare const volume_up: string
export declare const hashtag: string
export declare const security_time: string
export declare const star: string
export declare const bitcoin_card: string
export declare const folder_2: string
export declare const cd: string
export declare const clipboard_export: string
export declare const sun: string
export declare const home_2: string
export declare const bag_timer: string
export declare const bag_cross_1: string
export declare const danger: string
export declare const cloud_sunny: string
export declare const arrow_circle_down: string
export declare const message_square: string
export declare const folder_cross: string
export declare const more_2: string
export declare const arrow_right_4: string
export declare const mouse_circle: string
export declare const edit: string
export declare const percentage_circle: string
export declare const next: string
export declare const maximize_21: string
export declare const home_wifi: string
export declare const bluetooth_2: string
export declare const strongbox: string
export declare const wallet_add_1: string
export declare const receipt_2: string
export declare const emoji_normal: string
export declare const gallery_add: string
export declare const lifebuoy: string
export declare const volume_high: string
export declare const colorfilter: string
export declare const message_edit: string
export declare const pet: string
export declare const export_3: string
export declare const folder_cloud: string
export declare const export_2: string
export declare const arrow_left_1: string
export declare const flash_slash: string
export declare const send_square: string
export declare const unlock: string
export declare const forbidden_2: string
export declare const notification_status: string
export declare const star_slash: string
export declare const music_play: string
export declare const card_remove: string
export declare const forward_square: string
export declare const truck_time: string
export declare const designtools: string
export declare const eraser_1: string
export declare const woman: string
export declare const location_minus: string
export declare const bank: string
export declare const frame: string
export declare const judge: string
export declare const lock_1: string
export declare const video_play: string
export declare const arrow_swap_horizontal: string
export declare const receipt_item: string
export declare const global_refresh: string
export declare const magicpen: string
export declare const call_received: string
export declare const timer_1: string
export declare const home_1: string
export declare const three_square: string
export declare const search_zoom_out_1: string
export declare const music_library_2: string
export declare const bitcoin_refresh: string
export declare const simcard: string
export declare const play_remove: string
export declare const hierarchy: string
export declare const forbidden: string
export declare const ticket_discount: string
export declare const building_3: string
export declare const messages_2: string
export declare const setting_4: string
export declare const command: string
export declare const clock: string
export declare const wind_2: string
export declare const call_incoming: string
export declare const textalign_justifyright: string
export declare const slider_horizontal_1: string
export declare const courthouse: string
export declare const send_sqaure_2: string
export declare const message_programming: string
export declare const repeat_circle: string
export declare const direct_send: string
export declare const call: string
export declare const eye: string
export declare const wallet_add: string
export declare const mobile: string
export declare const gallery_edit: string
export declare const cloud_connection: string
export declare const personalcard: string
export declare const headphone: string
export declare const attach_square: string
export declare const bluetooth_rectangle: string
export declare const wallet_remove: string
export declare const path_square: string
export declare const location: string
export declare const profile_tick: string
export declare const device_message: string
export declare const electricity: string
export declare const receipt_edit: string
export declare const search_normal_1: string
export declare const arrange_square_2: string
export declare const glass_1: string
export declare const gift: string
export declare const setting_5: string
export declare const car: string
export declare const messages_3: string
export declare const forward_15_seconds: string
export declare const heart_remove: string
export declare const clock_1: string
export declare const language_square: string
export declare const tag_right: string
export declare const share: string
export declare const arrow_square_down: string
export declare const video_square: string
export declare const document_upload: string
export declare const video_horizontal: string
export declare const arrow_up: string
export declare const money: string
export declare const colors_square: string
export declare const folder_add: string
export declare const microscope: string
export declare const sort: string
export declare const messages_1: string
export declare const undo: string
export declare const video: string
export declare const video_vertical: string
export declare const external_drive: string
export declare const filter_square: string
export declare const security_safe: string
export declare const tree: string
export declare const activity: string
export declare const bitcoin_convert: string
export declare const box_time: string
export declare const filter: string
export declare const add_circle: string
export declare const money_send: string
export declare const pharagraphspacing: string
export declare const link_square: string
export declare const medal: string
export declare const arrow_swap: string
export declare const video_slash: string
export declare const calendar: string
export declare const lamp_charge: string
export declare const arrow_left: string
export declare const gas_station: string
export declare const buliding: string
export declare const data: string
export declare const ram: string
export declare const microphone_slash: string
export declare const keyboard_open: string
export declare const message_minus: string
export declare const volume_low: string
export declare const scanner: string
export declare const profile_circle: string
export declare const omega_circle: string
export declare const receipt_search: string
export declare const close_square: string
export declare const clipboard_import: string
export declare const heart_edit: string
export declare const wallet_money: string
export declare const task_square: string
export declare const cloud: string
export declare const lovely: string
export declare const shuffle: string
export declare const cup: string
export declare const mini_music_sqaure: string
export declare const diamonds: string
export declare const cpu_charge: string
export declare const pause: string
export declare const setting_2: string
export declare const box_tick: string
export declare const call_minus: string
export declare const forward: string
export declare const blend: string
export declare const bookmark: string
export declare const archive_2: string
export declare const arrow_down_2: string
export declare const shield_slash: string
export declare const status: string
export declare const note_square: string
export declare const rotate_right: string
export declare const programming_arrow: string
export declare const call_add: string
export declare const document_filter: string
export declare const level: string
export declare const lock_circle: string
export declare const receipt_minus: string
export declare const screenmirroring: string
export declare const math: string
export declare const favorite_chart: string
export declare const trend_down: string
export declare const component: string
export declare const strongbox_2: string
export declare const receipt_discount: string
export declare const maximize_circle: string
export declare const setting_3: string
export declare const volume_low_1: string
export declare const menu: string
export declare const like_shapes: string
export declare const building_4: string
export declare const search_zoom_out: string
export declare const sms_star: string
export declare const money_recive: string
export declare const send_1: string
export declare const repeate_one: string
export declare const security_user: string
export declare const note_21: string
export declare const bucket_square: string
export declare const volume_slash: string
export declare const chrome: string
export declare const save_add: string
export declare const finger_cricle: string
export declare const shopping_cart: string
export declare const happyemoji: string
export declare const airplane: string
export declare const calculator: string
export declare const discover_1: string
export declare const three_d_square: string
export declare const mouse: string
export declare const login_1: string
export declare const routing: string
export declare const music_square_remove: string
export declare const sms_edit: string
export declare const layer: string
export declare const truck_remove: string
export declare const man: string
export declare const receipt_text: string
export declare const lamp_slash: string
export declare const blend_2: string
export declare const mirror: string
export declare const menu_board: string
export declare const document_sketch: string
export declare const logout_1: string
export declare const slider_horizontal: string
export declare const graph: string
export declare const building: string
export declare const bezier: string
export declare const search_favorite: string
export declare const message_remove: string
export declare const cards: string
export declare const folder: string
export declare const alarm: string
export declare const copy_success: string
export declare const archive_1: string
export declare const color_swatch: string
export declare const arrow_down_1: string
export declare const timer: string
export declare const monitor: string
export declare const minus: string
export declare const three_d_cube_scan: string
export declare const card_add: string
export declare const wallet_minus: string
export declare const document_normal: string
export declare const scanning: string
export declare const element_plus: string
export declare const music_circle: string
export declare const gallery_export: string
export declare const moon: string
export declare const candle_2: string
export declare const weight: string
export declare const direct_normal: string
export declare const forward_10_seconds: string
export declare const voice_cricle: string
export declare const money_remove: string
export declare const card_tick: string
export declare const direct_notification: string
export declare const send_2: string
export declare const clipboard_text: string
export declare const align_left: string
export declare const refresh_2: string
export declare const calendar_remove: string
export declare const heart: string
export declare const data_2: string
export declare const bootstrap: string
export declare const figma: string
export declare const solana_sol: string
export declare const xiaomi: string
export declare const stellar_xlm: string
export declare const dropbox: string
export declare const eos_eos: string
export declare const nebulas_nas: string
export declare const cardano_ada: string
export declare const android: string
export declare const polygon_matic: string
export declare const celsius_cel_: string
export declare const js: string
export declare const siacoin_sc: string
export declare const wanchain_wan_1: string
export declare const google_drive: string
export declare const huobi_token_ht: string
export declare const tenx_pay: string
export declare const ui8: string
export declare const figma_1: string
export declare const civic_cvc: string
export declare const hedera_hashgraph_hbar: string
export declare const wanchain_wan: string
export declare const dent_dent: string
export declare const the_graph_grt: string
export declare const usd_coin_usdc: string
export declare const icon_icx: string
export declare const ftx_token_ftt: string
export declare const quant_qnt: string
export declare const wing_wing: string
export declare const emercoin_emc: string
export declare const zoom: string
export declare const chainlink_link: string
export declare const autonio_niox: string
export declare const dai_dai: string
export declare const python: string
export declare const blogger: string
export declare const augur_rep: string
export declare const zel_zel: string
export declare const nexo_nexo: string
export declare const ankr_ankr: string
export declare const iost_iost: string
export declare const polkadot_dot: string
export declare const decred_dcr: string
export declare const harmony_one: string
export declare const xd: string
export declare const ethereum_eth: string
export declare const spotify: string
export declare const java_script: string
export declare const trontron_trx: string
export declare const binance_coin_bnb: string
export declare const kyber_network_knc: string
export declare const maker_mkr: string
export declare const snapchat: string
export declare const ocean_protocol_ocean: string
export declare const avalanche_avax: string
export declare const binance_usd_busd: string
export declare const dash_dash: string
export declare const bitcoin_btc: string
export declare const velas_vlx: string
export declare const paypal: string
export declare const html_5: string
export declare const facebook: string
export declare const be: string
export declare const ontology_ont: string
export declare const whatsapp: string
export declare const google: string
export declare const celo_celo: string
export declare const tether_usdt: string
export declare const photoshop: string
export declare const stacks_stx: string
export declare const okb_okb: string
export declare const twitch: string
export declare const windows: string
export declare const polyswarm_nct: string
export declare const thorchain_rune: string
export declare const google_paly: string
export declare const youtube: string
export declare const html_3: string
export declare const illustrator: string
export declare const vibe_vibe: string
export declare const dribbble: string
export declare const enjin_coin_enj: string
export declare const trello: string
export declare const nem_xem: string
export declare const monero_xmr: string
export declare const ethereum_classic_etc: string
export declare const framer: string
export declare const xrp_xrp: string
export declare const slack: string
export declare const messenger: string
export declare const hex_hex: string
export declare const icon_1: string
export declare const apple: string
export declare const educare_ekt: string
export declare const litecoin_ltc: string
export declare const aave_aave: string
export declare const vuesax: string
export declare const theta_theta: string
